// Sample images used in the demo
module.exports = [
    {
      id:'0',
      branch: 'Chế xuất',
      company:
      [
        {
        image:'./image/CongNghe/apple.jpg',
        title:'Apple',
        href:'http://www.apple.com/',
        },
        {
        image:'./image/CongNghe/docomo.jpg',
        title:'Docomo',
        href:'https://www.nttdocomo.co.jp/',
        },
        {
        image:'./image/CongNghe/HTC.jpg',
        title:'HTC',
        href:'http://www.HTC.com',
        },
        {
        image:'./image/CongNghe/kyocera.jpg',
        title:'Kyocera',
        href:'http://www.kyoceramobile.com/',
        },
        {
        image:'./image/CongNghe/lenovo.jpg',
        title:'Lenovo',
        href:'http://www.lenovo.com',
        },
        {
        image:'./image/CongNghe/LG.jpg',
        title:'LG',
        href:'http://www.LG.com',
        },
        {
        image:'./image/CongNghe/samsung.jpg',
        title:'Samsung',
        href:'http://www.samsung.com',
        },
        {
        image:'./image/CongNghe/sharp.jpg',
        title:'Sharp',
        href:'http://www.sharp.com',
        },
        {
        image:'./image/CongNghe/SONY.jpg',
        title:'SONY',
        href:'http://www.SONY.com',
        },
        {
        image:'./image/CongNghe/toshiba.jpg',
        title:'Apple',
        href:'http://www.toshiba.com',
        },
              {
        image:'./image/CongNghe/apple.jpg',
        title:'Apple',
        href:'http://www.apple.com/',
        },
        {
        image:'./image/CongNghe/docomo.jpg',
        title:'Docomo',
        href:'https://www.nttdocomo.co.jp/',
        },
        {
        image:'./image/CongNghe/HTC.jpg',
        title:'HTC',
        href:'http://www.HTC.com',
        },
        {
        image:'./image/CongNghe/kyocera.jpg',
        title:'Kyocera',
        href:'http://www.kyoceramobile.com/',
        },
        {
        image:'./image/CongNghe/lenovo.jpg',
        title:'Lenovo',
        href:'http://www.lenovo.com',
        },
        {
        image:'./image/CongNghe/LG.jpg',
        title:'LG',
        href:'http://www.LG.com',
        },
        {
        image:'./image/CongNghe/samsung.jpg',
        title:'Samsung',
        href:'http://www.samsung.com',
        },
        {
        image:'./image/CongNghe/sharp.jpg',
        title:'Sharp',
        href:'http://www.sharp.com',
        },
        {
        image:'./image/CongNghe/SONY.jpg',
        title:'SONY',
        href:'http://www.SONY.com',
        },
        {
        image:'./image/CongNghe/toshiba.jpg',
        title:'Apple',
        href:'http://www.toshiba.com',
        },
      ],
    },
    {
      id:'1',
      branch: 'Nông Nghiệp',
      company:
      [
        {
        image:'./image/MyPham/avon.jpg',
        title:'avon',
        href:'http://www.avon.com',
        },
       {
        image:'./image/MyPham/biore.jpg',
        title:'biore',
        href:'http://www.biore.com',
        },
      {
        image:'./image/MyPham/esteelauder.jpg',
        title:'esteelauder',
        href:'http://www.esteelauder.com',
      },

      {
        image:'./image/MyPham/lancome.jpg',
        title:'lancome',
        href:'http://www.lancome.com',
        },
      {
        image:'./image/MyPham/loreal.jpg',
        title:'loreal',
        href:'http://www.loreal.com',
      },
      {
        image:'./image/MyPham/neutrogena.jpg',
        title:'neutrogena',
        href:'http://www.neutrogena.com',
        },
      {
        image:'./image/MyPham/nivea.jpg',
        title:'nivea',
        href:'http://www.nivea.com',
        },
      {
        image:'./image/MyPham/olay.jpg',
        title:'olay',
        href:'http://www.olay.com',
      },
      {
        image:'./image/MyPham/shiseido.jpg',
        title:'shiseido',
        href:'http://www.shiseido.com',
      },
      {
        image:'./image/MyPham/avon.jpg',
        title:'avon',
        href:'http://www.avon.com',
        },
       {
        image:'./image/MyPham/biore.jpg',
        title:'biore',
        href:'http://www.biore.com',
        },
      {
        image:'./image/MyPham/esteelauder.jpg',
        title:'esteelauder',
        href:'http://www.esteelauder.com',
      },

      {
        image:'./image/MyPham/lancome.jpg',
        title:'lancome',
        href:'http://www.lancome.com',
        },
      {
        image:'./image/MyPham/loreal.jpg',
        title:'loreal',
        href:'http://www.loreal.com',
      },
      {
        image:'./image/MyPham/neutrogena.jpg',
        title:'neutrogena',
        href:'http://www.neutrogena.com',
        },
      {
        image:'./image/MyPham/nivea.jpg',
        title:'nivea',
        href:'http://www.nivea.com',
        },
      {
        image:'./image/MyPham/olay.jpg',
        title:'olay',
        href:'http://www.olay.com',
      },
      {
        image:'./image/MyPham/shiseido.jpg',
        title:'shiseido',
        href:'http://www.shiseido.com',
      },     
      ],
    },
   {
      id:'2',
      branch: 'Nuoc Uong',
      company:
      [
        {
        image:'./image/NuocUong/asahi.jpg',
        title:'asahi',
        href:'http://www.asahi.jp',
        },
        {
        image:'./image/NuocUong/budweiser.jpg',
        title:'budweiser',
        href:'http://www.budweiser.com',
        },
        {
        image:'./image/NuocUong/carlsberg.jpg',
        title:'carlsberg',
        href:'http://www.carlsberg.com',
        },
        {
        image:'./image/NuocUong/cocacola.jpg',
        title:'cocacola',
        href:'http://www.cocacola.com',
        },
        {
        image:'./image/NuocUong/heineken.jpg',
        title:'heineken',
        href:'http://www.heineken.com',
        },
        {
        image:'./image/NuocUong/pepsi.jpg',
        title:'pepsi',
        href:'http://www.pepsi.com',
        },
        {
        image:'./image/NuocUong/redbull.jpg',
        title:'redbull',
        href:'http://www.redbull.com',
        },
        {
        image:'./image/NuocUong/sapporo.jpg',
        title:'sapporo',
        href:'sapporo.jp',
        },
        {
        image:'./image/NuocUong/saigon.jpg',
        title:'saigon',
        href:'http://www.saigon.com',
        },
        {
        image:'./image/NuocUong/tiger.jpg',
        title:'tiger',
        href:'http://www.tiger.com',
        },
       {
        image:'./image/NuocUong/asahi.jpg',
        title:'asahi',
        href:'http://www.asahi.jp',
        },
        {
        image:'./image/NuocUong/budweiser.jpg',
        title:'budweiser',
        href:'http://www.budweiser.com',
        },
        {
        image:'./image/NuocUong/carlsberg.jpg',
        title:'carlsberg',
        href:'http://www.carlsberg.com',
        },
        {
        image:'./image/NuocUong/cocacola.jpg',
        title:'cocacola',
        href:'http://www.cocacola.com',
        },
        {
        image:'./image/NuocUong/heineken.jpg',
        title:'heineken',
        href:'http://www.heineken.com',
        },
        {
        image:'./image/NuocUong/pepsi.jpg',
        title:'pepsi',
        href:'http://www.pepsi.com',
        },
        {
        image:'./image/NuocUong/redbull.jpg',
        title:'redbull',
        href:'http://www.redbull.com',
        },
        {
        image:'./image/NuocUong/sapporo.jpg',
        title:'sapporo',
        href:'sapporo.jp',
        },
        {
        image:'./image/NuocUong/saigon.jpg',
        title:'saigon',
        href:'http://www.saigon.com',
        },
        {
        image:'./image/NuocUong/tiger.jpg',
        title:'tiger',
        href:'http://www.tiger.com',
        },
      ],
    },
   {
      id:'3',
      branch: 'default',
      company:
      [
        {
        image:'./img/1.jpg',
        title:'Apple',
        href:'http://www.google.com',
        },
        {
        image:'./img/2.jpg',
        title:'Apple',
        href:'http://www.google.com',
        },
        {
        image:'./img/3.jpg',
        title:'Apple',
        href:'http://www.google.com',
        },
        {
        image:'./img/4.jpg',
        title:'Apple',
        href:'http://www.google.com',
        },
        {
        image:'./img/5.jpg',
        title:'Apple',
        href:'http://www.google.com',
        },
        {
        image:'./img/6.jpg',
        title:'Apple',
        href:'http://www.google.com',
        },
        {
        image:'./img/7.jpg',
        title:'Apple',
        href:'http://www.google.com',
        },
      
      ],
    },
];