// Sample images used in the demo
module.exports = [
    {
      id:'0',
      branch: 'Chế xuất',
      company:
      [
        {
        image:'./image/CongNghe/apple.jpg',
        title:'Apple',
        href:'https://www.apple.com/',
        },
        {
        image:'./image/CongNghe/docomo.jpg',
        title:'Docomo',
        href:'https://www.docomo.jp',
        },
        {
        image:'./image/CongNghe/HTC.jpg',
        title:'HTC',
        href:'https://www.HTC.com',
        },
        {
        image:'./image/CongNghe/kyocera.jpg',
        title:'Kyocera',
        href:'https://www.kyocera.jp',
        },
        {
        image:'./image/CongNghe/lenovo.jpg',
        title:'Lenovo',
        href:'https://www.lenovo.com',
        },
        {
        image:'./image/CongNghe/LG.jpg',
        title:'LG',
        href:'https://www.LG.com',
        },
        {
        image:'./image/CongNghe/samsung.jpg',
        title:'Samsung',
        href:'https://www.samsung.com',
        },
        {
        image:'./image/CongNghe/sharp.jpg',
        title:'Sharp',
        href:'https://www.sharp.com',
        },
        {
        image:'./image/CongNghe/SONY.jpg',
        title:'SONY',
        href:'https://www.SONY.com',
        },
        {
        image:'./image/CongNghe/toshiba.jpg',
        title:'Apple',
        href:'https://www.toshiba.com',
        },
              {
        image:'./image/CongNghe/apple.jpg',
        title:'Apple',
        href:'https://www.apple.com/',
        },
        {
        image:'./image/CongNghe/docomo.jpg',
        title:'Docomo',
        href:'https://www.docomo.jp',
        },
        {
        image:'./image/CongNghe/HTC.jpg',
        title:'HTC',
        href:'https://www.HTC.com',
        },
        {
        image:'./image/CongNghe/kyocera.jpg',
        title:'Kyocera',
        href:'https://www.kyocera.jp',
        },
        {
        image:'./image/CongNghe/lenovo.jpg',
        title:'Lenovo',
        href:'https://www.lenovo.com',
        },
        {
        image:'./image/CongNghe/LG.jpg',
        title:'LG',
        href:'https://www.LG.com',
        },
        {
        image:'./image/CongNghe/samsung.jpg',
        title:'Samsung',
        href:'https://www.samsung.com',
        },
        {
        image:'./image/CongNghe/sharp.jpg',
        title:'Sharp',
        href:'https://www.sharp.com',
        },
        {
        image:'./image/CongNghe/SONY.jpg',
        title:'SONY',
        href:'https://www.SONY.com',
        },
        {
        image:'./image/CongNghe/toshiba.jpg',
        title:'Apple',
        href:'https://www.toshiba.com',
        },
      ],
    },
    {
      id:'1',
      branch: 'Nông Nghiệp',
      company:
      [
        {
        image:'./image/MyPham/avo.jpg',
        title:'Apple',
        href:'google.com',
        },
       {
        image:'./image/MyPham/avo.jpg',
        title:'Apple',
        href:'google.com',
        },
      {
        image:'./image/MyPham/avo.jpg',
        title:'Apple',
        href:'google.com',
      },

      {
        image:'./image/MyPham/avo.jpg',
        title:'Apple',
        href:'google.com',
        },
      {
        image:'./image/MyPham/avo.jpg',
        title:'Apple',
        href:'google.com',
      },
      {
        image:'./image/MyPham/avo.jpg',
        title:'Apple',
        href:'google.com',
        },
      {
        image:'./image/MyPham/avo.jpg',
        title:'Apple',
        href:'google.com',
        },
      {
        image:'./image/MyPham/avo.jpg',
        title:'Apple',
        href:'google.com',
      },
      {
        image:'./image/MyPham/avo.jpg',
        title:'Apple',
        href:'google.com',
      },
      {
        image:'./image/MyPham/avo.jpg',
        title:'Apple',
        href:'google.com',
      },
      ],
    },
   {
      id:'2',
      branch: 'Công Nghiệp',
      company:
      [
        {
        image:'./image/3.jpg',
        title:'Apple',
        href:'google.com',
        },
        {
        image:'./image/3.jpg',
        title:'Apple',
        href:'google.com',
        },
        {
        image:'./image/1.jpg',
        title:'Apple',
        href:'google.com',
        },
        {
        image:'./image/1.jpg',
        title:'Apple',
        href:'google.com',
        },
        {
        image:'./image/1.jpg',
        title:'Apple',
        href:'google.com',
        },
        {
        image:'./image/1.jpg',
        title:'Apple',
        href:'google.com',
        },
        {
        image:'./image/1.jpg',
        title:'Apple',
        href:'google.com',
        },
      ],
    },
   {
      id:'3',
      branch: 'Nuôi bò',
      company:
      [
        {
        image:'./image/4.jpg',
        title:'Apple',
        href:'google.com',
        },
        {
        image:'./image/4.jpg',
        title:'Apple',
        href:'google.com',
        },
        {
        image:'./image/1.jpg',
        title:'Apple',
        href:'google.com',
        },
        {
        image:'./image/1.jpg',
        title:'Apple',
        href:'google.com',
        },
        {
        image:'./image/1.jpg',
        title:'Apple',
        href:'google.com',
        },
        {
        image:'./image/1.jpg',
        title:'Apple',
        href:'google.com',
        },
        {
        image:'./image/1.jpg',
        title:'Apple',
        href:'google.com',
        },
      ],
    },
];