// Sample images used in the demo
module.exports = [
    {
      id:'0',
      branch: 'Chế xuất',
      company:
      [
        {
        image:'./image/1.jpg',
        title:'Apple',
        href:'google.com',
        },
        {
        image:'./image/1.jpg',
        title:'Apple',
        href:'google.com',
        },
        {
        image:'./image/1.jpg',
        title:'Apple',
        href:'google.com',
        },
        {
        image:'./image/1.jpg',
        title:'Apple',
        href:'google.com',
        },
        {
        image:'./image/1.jpg',
        title:'Apple',
        href:'google.com',
        },
        {
        image:'./image/1.jpg',
        title:'Apple',
        href:'google.com',
        },
        {
        image:'./image/1.jpg',
        title:'Apple',
        href:'google.com',
        },
      ],
    },
    {
      id:'1',
      branch: 'Nông Nghiệp',
      company:
      [
        {
        image:'./image/2.jpg',
        title:'Apple',
        href:'google.com',
        },
        {
        image:'./image/2.jpg',
        title:'Apple',
        href:'google.com',
        },
        {
        image:'./image/2.jpg',
        title:'Apple',
        href:'google.com',
        },
        {
        image:'./image/2.jpg',
        title:'Apple',
        href:'google.com',
        },
        {
        image:'./image/2.jpg',
        title:'Apple',
        href:'google.com',
        },
        {
        image:'./image/1.jpg',
        title:'Apple',
        href:'google.com',
        },
        {
        image:'./image/1.jpg',
        title:'Apple',
        href:'google.com',
        },
      ],
    },
   {
      id:'2',
      branch: 'Công Nghiệp',
      company:
      [
        {
        image:'./image/3.jpg',
        title:'Apple',
        href:'google.com',
        },
        {
        image:'./image/3.jpg',
        title:'Apple',
        href:'google.com',
        },
        {
        image:'./image/1.jpg',
        title:'Apple',
        href:'google.com',
        },
        {
        image:'./image/1.jpg',
        title:'Apple',
        href:'google.com',
        },
        {
        image:'./image/1.jpg',
        title:'Apple',
        href:'google.com',
        },
        {
        image:'./image/1.jpg',
        title:'Apple',
        href:'google.com',
        },
        {
        image:'./image/1.jpg',
        title:'Apple',
        href:'google.com',
        },
      ],
    },
   {
      id:'3',
      branch: 'Nuôi bò',
      company:
      [
        {
        image:'./image/4.jpg',
        title:'Apple',
        href:'google.com',
        },
        {
        image:'./image/4.jpg',
        title:'Apple',
        href:'google.com',
        },
        {
        image:'./image/1.jpg',
        title:'Apple',
        href:'google.com',
        },
        {
        image:'./image/1.jpg',
        title:'Apple',
        href:'google.com',
        },
        {
        image:'./image/1.jpg',
        title:'Apple',
        href:'google.com',
        },
        {
        image:'./image/1.jpg',
        title:'Apple',
        href:'google.com',
        },
        {
        image:'./image/1.jpg',
        title:'Apple',
        href:'google.com',
        },
      ],
    },
];