// Sample images used in the demo
module.exports = [
  {
    id:'0',
    branch: 'default',
    company:
    [
      {
      image:'./../video/video1/5.mp4',
      title:'Apple',
      href:'http://www.google.com',
      },
      {
      image:'./../video/video1/2.mp4',
      title:'Apple',
      href:'http://www.google.com',
      },
      {
      image:'./../video/video1/3.mp4',
      title:'Apple',
      href:'http://www.google.com',
      },
      {
      image:'./../video/video1/4.mp4',
      title:'Apple',
      href:'http://www.google.com',
      },
      {
      image:'./../video/video1/5.mp4',
      title:'Apple',
      href:'http://www.google.com',
      },
      {
      image:'./../video/video1/5.mp4',
      title:'Apple',
      href:'http://www.google.com',
      },
      {
      image:'./../video/video1/2.mp4',
      title:'Apple',
      href:'http://www.google.com',
      },
    
    ],
  },
  {
    id:'1',
    branch: 'default',
    company:
    [
      {
      image:'./../video/fukoidan/5.mp4',
      title:'Apple',
      href:'http://www.google.com',
      },
      {
      image:'./../video/fukoidan/2.mp4',
      title:'Apple',
      href:'http://www.google.com',
      },
      {
      image:'./../video/fukoidan/3.mp4',
      title:'Apple',
      href:'http://www.google.com',
      },
      {
      image:'./../video/fukoidan/4.mp4',
      title:'Apple',
      href:'http://www.google.com',
      },
      {
      image:'./../video/fukoidan/5.mp4',
      title:'Apple',
      href:'http://www.google.com',
      },
      {
      image:'./../video/fukoidan/5.mp4',
      title:'Apple',
      href:'http://www.google.com',
      },
      {
      image:'./../video/fukoidan/2.mp4',
      title:'Apple',
      href:'http://www.google.com',
      },
    
    ],
  },
  {
       id:'2',
       branch: 'default',
       company:
       [
         {
         image:'./../video/video1/5.mp4',
         title:'Apple',
         href:'http://www.google.com',
         },
         {
         image:'./../video/video1/2.mp4',
         title:'Apple',
         href:'http://www.google.com',
         },
         {
         image:'./../video/video1/3.mp4',
         title:'Apple',
         href:'http://www.google.com',
         },
         {
         image:'./../video/video1/4.mp4',
         title:'Apple',
         href:'http://www.google.com',
         },
         {
         image:'./../video/video1/5.mp4',
         title:'Apple',
         href:'http://www.google.com',
         },
         {
         image:'./../video/video1/5.mp4',
         title:'Apple',
         href:'http://www.google.com',
         },
         {
         image:'./../video/video1/2.mp4',
         title:'Apple',
         href:'http://www.google.com',
         },
       ],
     },
     {
      id:'3',
      branch: 'default',
      company:
      [
        {
        image:'./../video/video1/5.mp4',
        title:'Apple',
        href:'http://www.google.com',
        },
        {
        image:'./../video/video1/2.mp4',
        title:'Apple',
        href:'http://www.google.com',
        },
        {
        image:'./../video/video1/3.mp4',
        title:'Apple',
        href:'http://www.google.com',
        },
        {
        image:'./../video/video1/4.mp4',
        title:'Apple',
        href:'http://www.google.com',
        },
        {
        image:'./../video/video1/5.mp4',
        title:'Apple',
        href:'http://www.google.com',
        },
        {
        image:'./../video/video1/5.mp4',
        title:'Apple',
        href:'http://www.google.com',
        },
        {
        image:'./../video/video1/2.mp4',
        title:'Apple',
        href:'http://www.google.com',
        },
      ],
    },
    {
      id:'4',
      branch: 'default',
      company:
      [
        {
        image:'./../video/video1/5.mp4',
        title:'Apple',
        href:'http://www.google.com',
        },
        {
        image:'./../video/video1/2.mp4',
        title:'Apple',
        href:'http://www.google.com',
        },
        {
        image:'./../video/video1/3.mp4',
        title:'Apple',
        href:'http://www.google.com',
        },
        {
        image:'./../video/video1/4.mp4',
        title:'Apple',
        href:'http://www.google.com',
        },
        {
        image:'./../video/video1/5.mp4',
        title:'Apple',
        href:'http://www.google.com',
        },
        {
        image:'./../video/video1/5.mp4',
        title:'Apple',
        href:'http://www.google.com',
        },
        {
        image:'./../video/video1/2.mp4',
        title:'Apple',
        href:'http://www.google.com',
        },
      ],
    },
 ];